// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANa9LTtHNh9BWmO7RZSt2C2y4shEJTagg',
    appId: '1:670044655896:web:583f65a479fbc9e3cdce6d',
    messagingSenderId: '670044655896',
    projectId: 'notification-test-app-9f24a',
    authDomain: 'notification-test-app-9f24a.firebaseapp.com',
    storageBucket: 'notification-test-app-9f24a.appspot.com',
    measurementId: 'G-3VCQSYH8J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUltgFKQDKbh40SAViFtNaXwLaq8G0mDo',
    appId: '1:670044655896:android:b95ff8fb5bb1f933cdce6d',
    messagingSenderId: '670044655896',
    projectId: 'notification-test-app-9f24a',
    storageBucket: 'notification-test-app-9f24a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_4Rzs9HDMeKGdlz7enSGJDNLRwGbVTI',
    appId: '1:670044655896:ios:e282e12d508f4305cdce6d',
    messagingSenderId: '670044655896',
    projectId: 'notification-test-app-9f24a',
    storageBucket: 'notification-test-app-9f24a.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe_4Rzs9HDMeKGdlz7enSGJDNLRwGbVTI',
    appId: '1:670044655896:ios:e282e12d508f4305cdce6d',
    messagingSenderId: '670044655896',
    projectId: 'notification-test-app-9f24a',
    storageBucket: 'notification-test-app-9f24a.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANa9LTtHNh9BWmO7RZSt2C2y4shEJTagg',
    appId: '1:670044655896:web:aa5a838c4aa59562cdce6d',
    messagingSenderId: '670044655896',
    projectId: 'notification-test-app-9f24a',
    authDomain: 'notification-test-app-9f24a.firebaseapp.com',
    storageBucket: 'notification-test-app-9f24a.appspot.com',
    measurementId: 'G-RJZHFDESZJ',
  );
}
